### ISSUE TITLE
不支持emoji和font-awsome

### ISSUE THREAD

**Issue by tohsakrat** [qq15725/modern-screenshot#11]
rt
一开始以为是字体跨域问题，后来仔细盘了一遍发现是一些特殊字体不能绘制。
不知道有没有办法解决QwQ

**Comment by qq15725** [comment]
这个似乎是我在去除 svg+xml 解析异常的 ascii null 控制字符时，错误的正则把 `\uD800-\uDFFF` 和 `\uFFFE-\uFFFF` 区域的 unicode 字符也移除导致的。

不过我发现多 unicode 的 emoji 在 svg+xml 解析时的字符宽度似乎和浏览器渲染不一致，例如

```
'😄'.split('').map(val => val.charCodeAt(0).toString(16)) 

// ['d83d', 'de04']
```

（这好像是另一个问题）
