### ISSUE TITLE
文心一言的图片无法导出的问题

### ISSUE THREAD

**Issue by gantrol** [qq15725/modern-screenshot#13]
文心一言在：https://yiyan.baidu.com/  
排队不用很久，今天普遍是一个多小时就到了

导出的插件是：https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.dark

网页原图：

![image](https://user-images.githubusercontent.com/31330732/225699912-a634003c-9f0e-49bb-9d14-6c3ff46ff5e0.png)

效果图：

![my-image-name (15)](https://user-images.githubusercontent.com/31330732/225700224-59a1e4bf-8bdc-4a3c-bfd2-4002c1df0ef9.png)

HTML格式为（链接的<id>是隐去的）：

```html

<div class="section-container html-wrap"><div class="custom-html"><p><img src="http://txt2img.cdn.bcebos.com/upload/<id>?x-bce-process=style/wm_ai"><br>好的，根据你的需求，我为你创作了一幅画作。<br>我的作画技能还在不断进化中，暂时还不支持对画作的修改和解释。<br>如果需要继续让我为你作画，请完整描述你的需求，如：“帮我画一枝晶莹剔透的牡丹花”。</p>
</div></div>
```

**Comment by qq15725** [comment]
悲伤的故事是，这么多天了还是没给我通过，有毒

**Comment by qq15725** [comment]
此处是 CDN 图片不支持 CORS 导致无法通过 JS 获取图像数据，以我目前了解的纯客户端应该无法解决。
