### ISSUE TITLE
Google web fonts not working in Firefox. Getting DOMException: CSSStyleSheet.cssRules error.

### ISSUE THREAD

**Issue by Dineshs91** [qq15725/modern-screenshot#16]
### Steps To Reproduce

1. Open a page with modern-screenshot in Firefox.
2. Use a Google web font in the container.
3. Generate image of the container (Containing the Google web font).

The following error shows up

```
Error while reading CSS rules from [https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@…;800&family=Slabo+27px:wght@300;400;500;700;800&display=swap](https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;700;800&family=Inter:wght@300;400;500;700;800&family=Lato:wght@300;400;500;700;800&family=Montserrat:wght@300;400;500;700;800&family=Open+Sans:wght@300;400;500;700;800&family=Poppins:wght@300;400;500;700;800&family=Prompt:wght@300;400;500;700;800&family=Public+Sans:wght@300;400;500;700;800&family=Raleway:wght@300;400;500;700;800&family=Roboto:wght@300;400;500;700;800&family=Slabo+27px:wght@300;400;500;700;800&display=swap) DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet
```

<details><summary>Error Message & Stack Trace</summary><p>
<img width="597" alt="error" src="https://user-images.githubusercontent.com/2663505/227834620-ff3d8f1f-b3f7-4da8-bb19-cd7ac1ad8569.png">

</p></details>

### Your Environment

- modern-screenshot: 4.4.9
- Browser: Firefox 111.0.1

**Comment by qq15725** [comment]
Since Firefox CORS policy is currently unavailable, I'll close the issue for now
