### ISSUE TITLE
domToPng 执行过程会阻塞 UI 线程渲染

### ISSUE THREAD

**Issue by jianghai** [qq15725/modern-screenshot#18]
执行 domToPng 前，react render 执行渲染，会有很长延迟

**Comment by qq15725** [comment]
大部分 CPU 占用是由于 `window.fetch` 获取图像和字体资源导致的，可以试试走 WebWorker 是否有改善

```ts
import { domToPng } from 'modern-screenshot'
// use vite
import workerUrl from 'modern-screenshot/worker?url'

domToPng(document.querySelector('#app'), {
  workerUrl,
  workerNumber: 1,
})
```

**Comment by qq15725** [comment]
> <img alt="image" width="606" src="https://user-images.githubusercontent.com/1535874/267242916-bea20ef6-aabc-463d-a968-a2cedc02c3ef.png"> @qq15725 这个import会报错

`?url` 是 Vite 支持的

你可以选择把 worker.js 下载下来放到工程资产中，然后填写同域的 http url

CDN

[https://unpkg.com/modern-screenshot/dist/worker.js](https://unpkg.com/modern-screenshot/dist/worker.js)

**Comment by Flourad** [comment]
@qq15725 好的 非常感谢～

**Comment by qq15725** [comment]
@Flourad https://github.com/qq15725/modern-screenshot/blob/v4.4.31/src/options.ts#L46

**Comment by Flourad** [comment]
> 

放在这个同一个目录下，可以直接这样引入么？
<img width="1265" alt="image" src="https://github.com/qq15725/modern-screenshot/assets/1535874/b97efbdd-5e08-4f05-8939-a6bd3e6e154b">

**Comment by Flourad** [comment]
> 

放在本地后，不能这样直接引入么？
import workerUrl from './worker';

**Comment by Flourad** [comment]
> 

求问，有没有vue项目本地引入web worker的实践，没有接触过web worker～如果放在目录下，好像js文件会被打包～
@qq15725

**Comment by qq15725** [comment]
@Flourad 例如放 `public/js/worker.js` 下，`workerUrl` 填写 `/js/worker.js` 这样

**Comment by Flourad** [comment]
> 

<img width="505" alt="image" src="https://github.com/qq15725/modern-screenshot/assets/1535874/0be49c34-1dee-4e27-b5f6-11b135574af7">改成这样，截图没反应，好像不会被执行

**Comment by Flourad** [comment]
<img width="693" alt="image" src="https://github.com/qq15725/modern-screenshot/assets/1535874/6c530ae1-377f-4c60-b496-52c8a4b2876f">
这种报错是正常的么？

**Comment by qq15725** [comment]
目前最后一步解码 `svg+xml` 成图像的部分无法在 WebWorker 中完成。

如果你截图 body 这种，可以查看下 `svg+xml` 的请求的大小，越大解码时间越久（过大会导致卡顿）。

可以尝试 `font: false` 先屏蔽字体的内嵌（一般来说会减少挺多大小）

**Comment by Flourad** [comment]
> 目前最后一步解码 `svg+xml` 成图像的部分无法在 WebWorker 中完成。
> 
> 如果你截图 body 这种，可以查看下 `svg+xml` 的请求的大小，越大解码时间越久（过大会导致卡顿）。
> 
> 可以尝试 `font: false` 先屏蔽字体的内嵌（一般来说会减少挺多大小）

这样会导致我的iconfont那些图标都没办法显示

**Comment by Lstoryc** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="505" src="https://user-images.githubusercontent.com/1535874/267264420-0be49c34-1dee-4e27-b5f6-11b135574af7.png">改成这样，截图没反应，好像不会被执行
> 
> 这个解决了，本地配置的问题，但是加了web worker之后 还是有点卡

大佬能分享下如何解决的？ @Flourad

**Comment by AlexAgustini** [comment]
Does someone know how to incorporate a Web Worker in Angular ?
