### ISSUE TITLE
Ios 设备 调用 domToDataUrl 图片无法加载

### ISSUE THREAD

**Issue by licc666** [qq15725/modern-screenshot#2]
设备： iPhoneXR
系统： 16.0
环境： safari，钉钉H5

具体呈现： 调用一次方法只呈现出一张图片
![image](https://user-images.githubusercontent.com/37287841/215993514-a7445b85-e150-4e4a-90a7-ba9fcc8af0e9.png)
![image](https://user-images.githubusercontent.com/37287841/215993670-ca4899c7-770b-4841-bb7d-d6de4d54aee2.png)
现解决方法： 如果画面有两张图片， 就要在 ios 端 额外 await 两次

**Comment by qq15725** [comment]
是最新版本 `modern-screenshot@^4.2.5` 把

https://codepen.io/qq15725/pen/PoBbOWm

我试试我的老 iPhone 7 能复现不

**Comment by licc666** [comment]
![动画](https://user-images.githubusercontent.com/37287841/216013285-94f02d99-5d2d-4144-84a9-df99ff978c39.gif)
复现过程

**Comment by qq15725** [comment]
恩，我也发现了，从图片 url 获取 MIME type 的正则有点问题，dataURI 类型异常导致的

https://github.com/qq15725/modern-screenshot/commit/41aa60138044350fe268a90ad3d31b13bcb5db96 `modern-screenshot@^4.2.6` 修复了，可以在试下

**Comment by licc666** [comment]
> 恩，我也发现了，从图片 url 获取 MIME type 的正则有点问题，dataURI 类型异常导致的
> 
> [41aa601](https://github.com/qq15725/modern-screenshot/commit/41aa60138044350fe268a90ad3d31b13bcb5db96) `modern-screenshot@^4.2.6` 修复了，可以在试下

![动画2](https://user-images.githubusercontent.com/37287841/216015635-39581af8-d0b1-4e5c-9d12-060f479779ec.gif)
不过还挺有趣的这个问题， 画面有几张图就要调用几次

**Comment by qq15725** [comment]
😄 没其他问题，我先把 issue 关闭了

**Comment by licc666** [comment]
> 😄 没其他问题，我先把 issue 关闭了

刚用相同设备测试还是存在同样的问题

**Comment by qq15725** [comment]
有办法在 https://codepen.io/qq15725/pen/PoBbOWm 复现个简单的例子吗 😂

**Comment by qq15725** [comment]
好像是问题还在，我再看看什么原因 😓

**Comment by licc666** [comment]
> 好像是问题还在，我再看看什么原因 😓

https://codepen.io/licc666/pen/XWByGKW?editors=1010
试下这个例子可以吗
但是并没有之前那样的有规律， 貌似是随机某张图片不加载

**Comment by qq15725** [comment]
旧版本的 webkit 当 `<img src="data:image/svg+xml;charset=utf-8,xxxxforeignObjectxxx" />` 使用 `decode` 会有一个 `Invalid image type.` 异常

https://bugs.webkit.org/show_bug.cgi?id=188347

---

新版本的 webkit 好像不会抛异常，正常 resolve `decode` 但是，似乎并没有正常解析 `<img src="data:image/svg+xml;" />`

https://bugs.webkit.org/show_bug.cgi?id=201243

导致当 `<img src="data:image/svg+xml;" />` 需要 `drawImage` 到 canvas 时并没有解析完，引起部分图像丢失

---

我要看下怎么确保 webkit 下的 svg+xml img 正常解析完

**Comment by licc666** [comment]
> 
难怪呢，就是在首次执行过后， 图像都能正常显示了

**Comment by qq15725** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/19576382/216231184-b579d552-7e76-459a-ae60-950635b513d7.png">

https://stackoverflow.com/questions/69949555/convert-svg-with-image-not-working-in-safari

估计其他库多少也有这个问题，我先瞅一瞅其他库，没好办法我就先提供个延迟 `drawImage` 的调用方式

**Comment by licc666** [comment]
> 

是的， html2canvas 也有问题，起初我采用的就是延迟方案，不过不是很理想

**Comment by qq15725** [comment]
😅 这貌似是 webkit 的 bug 研究了下，貌似只能延迟调用 n（图片数）次 `drawImage`，其他各种办法都没用

```
setTimeout(() => {
  context?.drawImage(loaded, 0, 0, canvas.width, canvas.height)
}, n)
```

**Comment by qq15725** [comment]
https://github.com/qq15725/modern-screenshot/commit/f083ddb49db4edfdf507ebef96c90f52752fafb5 先暂时这样修复把 😓 好像也可以正常解码

https://github.com/qq15725/modern-screenshot/blob/master/src/converts/image-to-canvas.ts#L14-L27

```ts
  // fix: image not decode when drawImage svg+xml in safari/webkit
  const counts = isOnlyAppleWebKit ? (resolved.context.images.size || 1) : 1
  for (let i = 0; i < counts; i++) {
    await new Promise<void>(resolve => {
      setTimeout(() => {
        try {
          context?.drawImage(loaded, 0, 0, canvas.width, canvas.height)
        } catch (error) {
          consoleWarn('Failed to image to canvas - ', error)
        }
        resolve()
      }, i)
    })
  }
```

**Comment by licc666** [comment]
> [f083ddb](https://github.com/qq15725/modern-screenshot/commit/f083ddb49db4edfdf507ebef96c90f52752fafb5) 先暂时这样修复把 😓 好像也可以正常解码
> 
> https://github.com/qq15725/modern-screenshot/blob/master/src/converts/image-to-canvas.ts#L14-L27
> 
> ```ts
>   // fix: image not decode when drawImage svg+xml in safari/webkit
>   const counts = isOnlyAppleWebKit ? (resolved.context.images.size || 1) : 1
>   for (let i = 0; i < counts; i++) {
>     await new Promise<void>(resolve => {
>       setTimeout(() => {
>         try {
>           context?.drawImage(loaded, 0, 0, canvas.width, canvas.height)
>         } catch (error) {
>           consoleWarn('Failed to image to canvas - ', error)
>         }
>         resolve()
>       }, i)
>     })
>   }
> ```

是的， 暂时只有多次调用的解决方法了， 感谢

**Comment by XboxYan** [comment]
请问现在有更好的解决办法了吗？看来这好像是Safari的bug，并不是库的问题，我将一段带有`base64`资源的`svg`直接在canvas中绘制处理，会出出现首次缺失的问题

```html
 <svg id="svg" width="200" height="200" xmlns="http://www.w3.org/2000/svg">
    <image href="data:image/png;base64,iV..."/>
    <text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle">SVG</text>
</svg>
```

https://codepen.io/xboxyan/pen/wBvvorp 


<img width="253" alt="Image" src="https://github.com/user-attachments/assets/29d1a80d-7b19-4fc0-b187-36b2d7d6cc5e" />

**Comment by tyranasaurus** [comment]
@XboxYan did you come up with anything or a good fix? Encountering similar issues, unfortunately.
