### ISSUE TITLE
Fonts are not applied in Safari.

### ISSUE THREAD

**Issue by Funncy** [qq15725/modern-screenshot#21]
I am currently using this library to develop a requirement to store a specific component. Thanks for developing it.

It is working fine in chrome.
However, in safari, the font is not being applied and is coming up with the default font. 

In Chrome
![download (35)](https://user-images.githubusercontent.com/22514912/233540384-9cb266af-9597-4252-bacf-3fbad7a1c355.png)

In Safari
![download-4](https://user-images.githubusercontent.com/22514912/233540400-c32a6866-5da9-4134-b14b-534a3589cbde.png)

my code :
```
 await domToCanvas(imageDiv, {
      scale: 2,
      backgroundColor: 'white',
      drawImageInterval: 1000,
    });

    const canvas = await domToCanvas(imageDiv, {
      scale: 2,
      backgroundColor: 'white',
      drawImageInterval: 1000,
    });
```

`  <div className="absolute bottom-[-1000px]">
        <div
          id="capture-area"
          className="relative z-[-2] w-[340px] h-[370px] "
          ref={imageShareRef}
        >
          <div className="relative top-[10px]">
            <Diary.CardImage
              imageSrc={feed['운동 인증샷']}
              sportsKind={feed['운동 종목']}
              workout={feed.운동량}
              emotion={feed.감정량}
              goal={feed['작성자 되고싶은나'] ?? ''}
              goalPercent={feed.goalGauge}
              pictureTime={formattingTime}
            />
          </div>
        </div>
      </div>`

### Your Environment

- modern-screenshot: [e.g. 4.4.9]
- Browser: Chrome (111.0.5563.146)
Safari 16.2(18614.3.7.1.5)

**Comment by Funncy** [comment]
And in Safari, it takes three calls to domToCanvas to upload the image correctly

First
![download-11](https://user-images.githubusercontent.com/22514912/233540970-e07d40eb-7b30-4466-9d25-0b2d41e506d5.png)

Second
![download-12](https://user-images.githubusercontent.com/22514912/233540981-31c0697c-459e-4d13-8168-db511a9415d3.png)

Thrid
![download-13](https://user-images.githubusercontent.com/22514912/233540996-725f2feb-2b5c-460b-83b4-59f439383681.png)

**Comment by qq15725** [comment]
Are there still problems with svg+xml inline image decoding in Safari? The simple example I tested seems to be normal

modern-screenshot: 4.4.15

https://codepen.io/qq15725/pen/PoBbOWm

<img width="828" alt="image" src="https://user-images.githubusercontent.com/19576382/233545524-a2667514-5f56-46e2-918d-c359ee81ffae.png">

You need to see how the font is imported. Is there a warning of CORS

**Comment by Funncy** [comment]
Thanks for the quick reply.
The issue of calling and saving the image multiple times is not a pressing issue for me at the moment - the library is fast enough for me to call it 3 times. (I'll try to reproduce the symptoms with codepen or something later).

The more pressing issue for me is
I'm currently developing a webapp made with Nextjs and wrapped in Flutter.
I'm using native webviews.
On the iPhone mobile webview, when I apply scale, it doesn't work and I get a degraded quality. Same thing when I give quality to 1.
I have to save it in high quality now. 
Could you please give me some whiteness in this regard?

**Comment by Funncy** [comment]
Oh and by the way, the font is fixed, thanks.

**Comment by qq15725** [comment]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/19576382/233548293-2f1460fb-aee3-4c9b-b552-0e5a8f05338d.png">

then

```ts
canvas.toDataURL('image/png', 1)
```

canvas should only export png like this

**Comment by qq15725** [comment]
The canvas default dpi is 96 which is probably your problem

**Comment by Funncy** [comment]
`
const canvas = await domToCanvas(node, {
      scale: 3,
      backgroundColor: 'white',
      drawImageInterval: 1000,
      quality: 1,
    });

    if (checkWebApp()) {
      const result = await saveImageToGallery(canvas.toDataURL('image/png', 1));
      if (result === undefined) {
        setToast({
          content: '오류가 발생했습니다.',
        });
        return;
      }

      setToast({
        content: '저장되었습니다.',
      });
      return;
    } else {
      FileSaver(canvas.toDataURL('image/png', 1));
    }
`

Above is my code.

scale doesn't work on mobile webview 
It works fine in desktop safari.

**Comment by Funncy** [comment]
As I continue to test, the issue with degradation seems to be more about quality than scale.

It only happens on the iPhone mobile webview.

**Comment by qq15725** [comment]
You can also try `domToPng`, I will handle png `dpi` value based on `scale`

origin width: 1280
origin height: 105.5
scale: 4

output width: 5120
output height: 422
dpi: 384

<img width="773" alt="image" src="https://user-images.githubusercontent.com/19576382/233554303-6fa9ec65-2cee-4746-ac34-5971457d2bd4.png">

**Comment by Funncy** [comment]
Thank you, strangely it looks degraded in the iPhone gallery but when I put it on Instagram it looks fine. thank you!!!
