### ISSUE TITLE
How Screenshot of hidden div using modern-screenshort

### ISSUE THREAD

**Issue by jaytnw** [qq15725/modern-screenshot#26]
How to take screenshots of a hidden div? Similar to using html2canvas code below.

```
[html2canvas(mydiv,](url) {
    onclone: function (clonedDoc) {
        clonedDoc.getElementById('mydiv').style.display = 'block';
    }
}).then((canvas)=>{
//your onrendered function code here
})
```

**Comment by qq15725** [comment]
Use `onCloneNode` option

```ts
import { domToPng } from 'modern-screenshot'

domToPng(mydiv, {
  onCloneNode: function (clonedDoc) {
    clonedDoc.getElementById('mydiv').style.display = 'block';
  }
})
```

**Comment by jaytnw** [comment]
I got an error as follows

`TypeError: clonedDoc.getElementById is not a function`

my code

```
   const mydiv= document.getElementById("mydiv")

domToPng(div, {
                onCloneNode: function (clonedDoc) {
                    clonedDoc.getElementById('frontCardLoad').style.display = 'block';
                }
            }).then(dataUrl => {
                const link = document.createElement('a')
                link.download = 'frontCard_' + dataInputs.petThaiFName + '.png'
                link.href = dataUrl
                link.click()
            })
```

**Comment by qq15725** [comment]
I'm sorry I didn't look closely, is this what you want

```ts
onCloneNode: function (cloned) {
  // cloned === you mydiv
  cloned.querySelector('#child-element-id').style.display = 'block';
}
```

**Comment by jaytnw** [comment]
I still got an error as follows

`TypeError: Cannot read properties of null (reading 'style')`

my code

```
const mydiv = document.getElementById("mydiv")
       domToPng(mydiv , {
                onCloneNode: function (cloned) {
                    cloned.querySelector('#mydiv').style.display = 'block';
                }
            }).then(dataUrl => {
                const link = document.createElement('a')
                link.download = 'frontCard_' + dataInputs.petThaiFName + '.png'
                link.href = dataUrl
                link.click()

            })
```

**Comment by jaytnw** [comment]
It not work when I use onCloneNode. domToPng return base64 is "data:"

**Comment by qq15725** [comment]
I need a minimal reproduction to debug your issue, thanks!

[Playground for https://codesandbox.io](https://codesandbox.io/s/modern-screenshot-lxhrev?file=/index.html)

[Playground for https://codepen.io](https://codepen.io/qq15725/pen/VwGeqwa)

[Playground for https://play.vuejs.org](https://play.vuejs.org/#eNplkk1rg0AQhv/KsFBqIFFpycWYQA899FAIpb3tZdGNmrof7I75IPjfO64mDeSguO++88y7417Ym7XxoZMsY7kvXGMRvMTObrhulDUO4QKlUd9mqyvoYeeMgmdlSun0gvxSal8bfL5zO7mbg9GfptMoy1sN9SAX14XRHsEZg+8trAd3NLuqpUDx8/XxL3N9A0XCn3UB0QzWG7hwDVd3fBBtJ6lGHEVDjClsNLYYd+eUyxeilRm8QE/g4cmT8cB0VFqgVLYVKGkFkJfNYciw5mzEcAZFK7yfBM6CjYzeCr3ZtuJcOcpZEnMQAiMhSGDTd6MqyLwrqH6KTUSP51aSgk5ovzNOZWPIKI2XMwjqkChaLNOnOQzv2YrKEoLmyV1eWgZUaBsP+cYBARybEusMXtPUnlajVMumqvFe68MoAoDN2fgfF0rYeO+NpnsRWHza8JxlVzpnDxdh2OWsRrQ+S5JO298qLoxKHow0HI9Jo0t5itWeqFOSnvV/3hTgRw==)
