### ISSUE TITLE
文字渐变不支持

### ISSUE THREAD

**Issue by jianghai** [qq15725/modern-screenshot#28]
![image](https://github.com/qq15725/modern-screenshot/assets/2820736/31529a0c-a95f-46f0-b40a-352f9c8dec78)

chrome: v113.0.5672.92
modern-screenshot: v4.4.20

**Comment by jianghai** [comment]
怀疑是 chrome 升级导致
给 dom 设置 webkitBackgroundClip ，比如 document.body.style.webkitBackgroundClip = "text"; 
会自动去除 webkit 前缀，但是 chrome 渲染还是正常

**Comment by qq15725** [comment]
可以尝试先升级 `modern-screenshot` 到最新版试试, 最新版文字渐变应该是正常的

**Comment by jianghai** [comment]
> 可以尝试先升级 `modern-screenshot` 到最新版试试, 最新版文字渐变应该是正常的

不行，手动 css 加了 -webkit-background-clip: text 后截图正常

**Comment by qq15725** [comment]
通过 JS 设置 style.webkitBackgroundClip 好像是不行，具体我也不清楚（浏览器行为），我这边处理[也是手动加
 class 以保证这个特性](https://github.com/qq15725/modern-screenshot/blob/main/src/copy-css-styles.ts#L36)

目前应该只能支持 `-webkit-background-clip: text`

1. 使用 JS 添加 class
2. 使用 css

**Comment by jianghai** [comment]
> 通过 JS 设置 style.webkitBackgroundClip 好像是不行，具体我也不清楚（浏览器行为），我这边处理[也是手动加 class 以保证这个特性](https://github.com/qq15725/modern-screenshot/blob/v4.4.26/src/copy-css-styles.ts#L36)
> 
> 目前应该只能支持通过 CSS 的 `-webkit-background-clip: text`
> 
> 1. 使用 JS 添加 class
> 2. 使用 CSS

那不应该有问题，库已经做了适配了
