### ISSUE TITLE
Default font on Firefox

### ISSUE THREAD

**Issue by mateusfg7** [qq15725/modern-screenshot#29]
Before all, **thanks for this lib**, I am searching for a related thing for a long time!

# Problem
I am having issues with font on Firefox, when I save the image using `domToPng`, the browser default font is used instead my custom font.

_preview_
![image](https://github.com/qq15725/modern-screenshot/assets/40613276/a6281219-4cf9-443e-8fd1-4be556bee36b)

_result_
![yutyiytuituyrty](https://github.com/qq15725/modern-screenshot/assets/40613276/0ed7762b-5fc0-406c-a940-551bf798f91e)

# Environment

**Browser**: Firefox 113.0.2
**Framework**: Next.js@13.4.4
**modern-screenshot**: 4.4.25
**Related Libs**: react@18.2.0, tailwindcss@3.3.2, postcss@8.4.24
**Repo**:  https://github.com/mateusfg7/rifa
**Related source**:
- [`tailwind.config.js`  where I setup my custom font](https://github.com/mateusfg7/rifa/blob/2f21830b600d24916043f3e9b4f18c157991c414/tailwind.config.js#L10)
- [`layout.tsx` where I use `next/font`  to get font classes](https://github.com/mateusfg7/rifa/blob/2f21830b600d24916043f3e9b4f18c157991c414/src/app/layout.tsx)
- [function that run `domToPng`](https://github.com/mateusfg7/rifa/blob/2f21830b600d24916043f3e9b4f18c157991c414/src/components/card/index.tsx#L32)

# Additional information

I also tested on Chrome and works fine. The problem only occurs on production environment, when I run the app on development environment all works fine.

**Comment by qq15725** [comment]
Fixed, please try upgrading to modern-screenshot@^4.4.26

**Comment by mateusfg7** [comment]
Solved, thanks again!
