### ISSUE TITLE
生产的图片很模糊，如何调整呢

### ISSUE THREAD

**Issue by wenlc000** [qq15725/modern-screenshot#31]
### Steps To Reproduce

[Playground for https://codesandbox.io](https://codesandbox.io/s/modern-screenshot-lxhrev?file=/index.html)

[Playground for https://codepen.io](https://codepen.io/qq15725/pen/VwGeqwa)

[Playground for https://play.vuejs.org](https://play.vuejs.org/#eNplkk1rg0AQhv/KsFBqIFFpycWYQA899FAIpb3tZdGNmrof7I75IPjfO64mDeSguO++88y7417Ym7XxoZMsY7kvXGMRvMTObrhulDUO4QKlUd9mqyvoYeeMgmdlSun0gvxSal8bfL5zO7mbg9GfptMoy1sN9SAX14XRHsEZg+8trAd3NLuqpUDx8/XxL3N9A0XCn3UB0QzWG7hwDVd3fBBtJ6lGHEVDjClsNLYYd+eUyxeilRm8QE/g4cmT8cB0VFqgVLYVKGkFkJfNYciw5mzEcAZFK7yfBM6CjYzeCr3ZtuJcOcpZEnMQAiMhSGDTd6MqyLwrqH6KTUSP51aSgk5ovzNOZWPIKI2XMwjqkChaLNOnOQzv2YrKEoLmyV1eWgZUaBsP+cYBARybEusMXtPUnlajVMumqvFe68MoAoDN2fgfF0rYeO+NpnsRWHza8JxlVzpnDxdh2OWsRrQ+S5JO298qLoxKHow0HI9Jo0t5itWeqFOSnvV/3hTgRw==)

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

### Your Environment

- modern-screenshot: [e.g. 4.4.9]
- Browser: [e.g. chrome 111.0.5563.64]

**Comment by qq15725** [comment]
浏览器 `Canvas` 只能导出 96 DPI 的图片

`modern-screenshot` 选项中提供了 `scale` 可以在 `domToPng` 和 `domToJpeg` [导出更高 DPI](https://github.com/qq15725/modern-screenshot/blob/v4.4.26/src/change-png-dpi.ts#L44)

```ts
import { domToPng } from 'modern-screenshot'

// DPI = 96 * 2
domToPng(dom, { scale: 2 })
```
