### ISSUE TITLE
背景图是 http 资源时，生成图片有概率丢失

### ISSUE THREAD

**Issue by jianghai** [qq15725/modern-screenshot#34]
background-image: url('https://xx')

**Comment by qq15725** [comment]
查看是否传递了太短的 timeout 默认是 30s 

```ts
domToPng({
  timeout: 30000,
})
```

查看是否存在加载的网络请求

如果完全没加载，可能需要提供完整的测试样本

**Comment by lorenzhh** [comment]
I had the same issue, I don't know why it may happens. 
So I configured the domToPng not to use catch by adding:
      
fetch: { 
   bypassingCache: true 
},
