### ISSUE TITLE
html元素中包含emoji表情时，生成报错

### ISSUE THREAD

**Issue by lujihong** [qq15725/modern-screenshot#35]
### Steps To Reproduce
html元素中包含emoji表情时，生成报错：String contained illegal UTF-16 sequence.

IOS 16.5.1  微信  8.0.39

**Comment by lujihong** [comment]
修改以下代码就没问题了：
      function de(e) {
        const t = new XMLSerializer().serializeToString(e)
        .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\uFFFE\uFFFF]/ug, ""); //方法一：去掉\uD800-\uDFFF
        //.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\uD800-\uDFFF\uFFFE\uFFFF]/ug, ""); //方法二：注释掉全部
        return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(t)}`;
      }

**Comment by qq15725** [comment]
这段代码是过滤掉 xml 中 null 控制符的，估计是误伤两个 unicode 组成的 emoji 了，可以提供下异常的 emoji

**Comment by lujihong** [comment]
😊😘  我随便测试了几个emoji都有问题

**Comment by qq15725** [comment]
<img width="873" alt="image" src="https://github.com/qq15725/modern-screenshot/assets/19576382/48e7cf6e-84f3-401b-adea-0bdd86cc2bf6">

https://modern-screenshot.vercel.app/

这两个 emoji 我浏览器是没问题，看是环境问题还是其他 emoji ，最好是把整段有问题的提供下

**Comment by qq15725** [comment]
4.4.27 支持了只启用部分特性

```ts
domToPng({
  features: {
    // 不启用移除控制符
    removeControlCharacter: false,
  }
})
```

**Comment by jeremiecarlson** [comment]
I have the same issue - iOS only - no issue on desktop Safari
Using domToBlob in my use case.
Setting `removeControlCharacter` to true/false makes no difference to the error

**Comment by jeremiecarlson** [comment]
Using the vercel demo app you can reproduce: 

<img width="1135" alt="Screenshot 2023-12-13 at 1 30 56 PM" src="https://github.com/qq15725/modern-screenshot/assets/862351/aad3eae1-9fc9-48e1-bfe4-a006eb086a2b">
