### ISSUE TITLE
当使用 `document.fonts` 的方式添加字体，生成的图片会丢失文字的字体样式

### ISSUE THREAD

**Issue by chenzn1** [qq15725/modern-screenshot#39]
### Steps To Reproduce
```
const fontFile = new FontFace(fontFamily, `url(${fontUrl})`);
document.fonts.add(fontFile);
fontFile.load();
```
dom 是有添加的字体样式，但生成的图片没有
### Your Environment

- modern-screenshot: 4.4.26
- Browser: chrome 115.0.5790.170

**Comment by qq15725** [comment]
`document.fonts` 没有附加对应的 DOM 对象，无法内嵌到 `svg+xml` 中，在 Web 标准没支持前应该无法处理。只能处理 `style` 方式新增的字体。
