### ISSUE TITLE
No Firefox support 🦊

### ISSUE THREAD

**Issue by duraes-antonio** [qq15725/modern-screenshot#4]
Hello, bro, thanks for make this lib!

After some tests on a rich page, I noticed that it doesn't work on Firefox browser even with a simple case. Unfortunately, there is no console error or warning to help identify the problem.

Minimal scenario to reproduce:
https://codepen.io/qq15725/pen/PoBbOWm

**Comment by qq15725** [comment]
You can try the `modern-screenshot@4.2.13` version to see if the exception has been fixed

**Comment by duraes-antonio** [comment]
Thanks, bro! That's solved.
