### ISSUE TITLE
chrome 和 Firefox 不同平台的截图性能

### ISSUE THREAD

**Issue by wuyafeiya** [qq15725/modern-screenshot#40]
相同的网络环境 相同的代码片段  截图执行时间 在Firefox要等很久

![截屏2023-08-14 17 56 50](https://github.com/qq15725/modern-screenshot/assets/49944076/e881c02f-f9e5-444c-a79a-81b92ea4890c)
### 环境
- macos
- chrome 和 Firefox

### 执行时间
 
- chrome       0.2ms
- Firefox        6000+ms

**Comment by qq15725** [comment]
可以通过 `fixSvgXmlDecode` 关闭

```
domToPng({
  features: {
    fixSvgXmlDecode: false,
  },
})
```

或者查看为什么要这样做

https://github.com/bubkoo/html-to-image/issues/420#issuecomment-1667079108

**Comment by wuyafeiya** [comment]
谢谢 性能得到了一些优化 但是还是比不过chrome 但是已经可以满足需求 感谢
