### ISSUE TITLE
Bug deleting primary colors such as #000000(black)

### ISSUE THREAD

**Issue by saseungmin** [qq15725/modern-screenshot#59]
Hello, thanks for a great tool.

### Steps To Reproduce

- live example

https://codesandbox.io/s/thirsty-curran-5nr943?file=/src/App.tsx

![test (1)](https://github.com/qq15725/modern-screenshot/assets/60910665/9d5e66c2-b143-4fa7-b2ac-e2bdd2d771ab)

- If you look at the example code, it seems to delete the primary color. (h1 tag color: black or `#000000`)
- As my temporary solution, I applied the value `#000001` which is similar to `#000000` (h2 tag)

### Your Environment

- modern-screenshot: 4.4.33
- Browser: chrome  119.0.6045.123, safari, ios same issue
- OS: mac sonoma 14

**Comment by qq15725** [comment]
4.4.34 fixed

![test](https://github.com/qq15725/modern-screenshot/assets/19576382/e2892767-55c5-4f07-b7fd-93317eb00464)
