### ISSUE TITLE
Performance issues with copying styles with `getComputedStyle`

### ISSUE THREAD

**Issue by qq15725** [qq15725/modern-screenshot#6]
- [copy-css-styles.ts](https://github.com/qq15725/modern-screenshot/blob/master/src/copy-css-styles.ts)
- [get-default-style.ts](https://github.com/qq15725/modern-screenshot/blob/master/src/get-default-style.ts)

**Comment by qq15725** [comment]
It shouldn't work out for now ~

**Comment by Tar-Palantir** [comment]
Hello, I have used your library, it's great but have performance issue when my DOM is complicate, `getComputedStyle` may block page render. Do you have any plan trying to solve this issue? Or any idea about it?
