### ISSUE TITLE
Add option to selectively include style properties when cloning element

### ISSUE THREAD

**Issue by aeharding** [qq15725/modern-screenshot#62]
Hello!

I have an optimization [on my fork](https://github.com/aeharding/modern-screenshot/commit/d48ce73b181830faf3d586bc080bee2690781bee#diff-2123f97b7bf9480a61717c843425e483e8d97819592e8c04e4e149eb65b451e8R210) called `includeStyleProperties`. It can be passed a list of CSS properties that will be copied over during node cloning.

This can improve performance 2 times or more in my use (however, you have to specify all CSS properties, so it is really for performance critical situations only). It is inspired [from this pull request](https://github.com/bubkoo/html-to-image/pull/436/files).

If you are open to adding support for this feature, I will make a PR. :) Please let me know.

**Comment by qq15725** [comment]
Of course you can 🚀
