### ISSUE TITLE
新必应聊天导出后，大部分引用的链接由一行变成两行

### ISSUE THREAD

**Issue by gantrol** [qq15725/modern-screenshot#8]
在[必应聊天分享与保存](https://github.com/gantrol/Bing-Chat-Saver)项目引用了你这个库，效果很不错的。

只是目前还有一点疑问，怎么才能把变成文本两行的引用调整成一行？

### 效果图
![image](https://user-images.githubusercontent.com/31330732/218899483-8f64d453-656a-459b-a3f0-d39af3604a3d.png)

### 原网页
![image](https://user-images.githubusercontent.com/31330732/218899625-997df76c-061a-4da8-aebf-81ae3584de66.png)

### 引用部分的css
![引用的css2](https://user-images.githubusercontent.com/31330732/218899696-55d62ca5-c2f3-4cfd-a2b2-c3961885283d.png)

**Comment by qq15725** [comment]
我似乎无法提交 bing chat 的加入等候列表，可以提供个最小的复现片段吗 😓

https://codepen.io/qq15725/pen/poOoQZz

**Comment by qq15725** [comment]
<img width="104" alt="image" src="https://user-images.githubusercontent.com/19576382/218916617-e1e00001-bdb5-42af-8793-fdfa6f3bd841.png">

字宽 67px

<img width="102" alt="image" src="https://user-images.githubusercontent.com/19576382/218916669-bf90ef9f-8a5d-4426-b119-09c5f96a80cd.png">

字宽 65px

貌似是这 2px 导致的，不知道是不是 font-size 或者 font-family 截图时取值的问题

**Comment by gantrol** [comment]
> 我似乎无法提交 bing chat 的加入等候列表，可以提供个最小的复现片段吗 😄
> 
> https://codepen.io/qq15725/pen/poOoQZz

分析了下，不知道是不是字体的问题，链接的字在原网页上偏细，而在codepen复现的时候，字跟输出的图片一样粗。

原网页前端比较复杂，个人没找出为何字那么细的原因，抱歉。

**Comment by qq15725** [comment]
1. 可能需要查看 var(--cib-font-text) 和对应字体值的 @font-face css 定义部分（写法）
2. 尝试检查 `data:image/svg+xml;` 请求中是否正常内嵌该字体，类似
<img width="957" alt="image" src="https://user-images.githubusercontent.com/19576382/218919339-1a53edcf-042e-4a96-b09d-1d216a1c31d0.png">

或者等我申请个 Bing Chat 再试试 😄

**Comment by gantrol** [comment]
> 2. 尝试检查 `data:image/svg+xml;` 请求中是否正常内嵌该字体，类似

disable cache后，仅有一个下载svg的请求

> 1. 可能需要查看 var(--cib-font-text) 和对应字体值的 @font-face css 定义部分（写法）

```css
var(--cib-font-text): -apple-system, Roboto, SegoeUI, "Segoe UI", "Helvetica Neue", Helvetica, "Microsoft YaHei", "Meiryo UI", Meiryo, Arial Unicode MS, sans-serif
```

```css
@font-face {
font-family: 'Roboto Light';
src: url(/sa/simg/Roboto_Light.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

@font-face {
font-family: 'Roboto';
src: url(/sa/simg/Roboto_Regular.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

@font-face {
font-family: 'Roboto Semibold';
src: url(/sa/simg/Roboto_Semibold.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

@font-face {
font-family: 'Roboto';
font-weight: 200;
src: url(/sa/simg/Roboto_Light.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

@font-face {
font-family: 'Roboto';
font-weight: 300;
src: url(/sa/simg/Roboto_Light.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

@font-face {
font-family: 'Roboto';
font-weight: 600;
src: url(/sa/simg/Roboto_Semibold.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

@font-face {
font-family: 'Roboto';
font-weight: 700;
src: url(/sa/simg/Roboto_Semibold.woff2) format('woff2');
unicode-range: U+0-FF,U+131,U+152-153,U+2BB-2BC,U+2C6,U+2DA,U+2DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215
}

**Comment by qq15725** [comment]
感谢，这应该是我的一个 bug，当 `font-family` 出现多个字体时会被过滤掉不处理内嵌 font

可以尝试 `modern-screenshot@4.3.4` 如果还存在这个问题可以再打开 issue 

p: Bing Chat 在申请了 😄

**Comment by gantrol** [comment]
问题还是有，不过可能不是这个库的缺陷。问题与`font-weight: 500;`相关

![image](https://user-images.githubusercontent.com/31330732/218938477-7bfbb3d2-c88a-4e31-8cf9-8720c03228f2.png)


我将引用部分的`font-weight`改为400，导出居然没有问题（两个版本都一样）

![image](https://user-images.githubusercontent.com/31330732/218938865-9ca67ed5-1f7c-41bd-ba64-59d6d3177f65.png)

**Comment by qq15725** [comment]
😂 那还是等晚些申请通过了，我自己试试确认下问题

**Comment by plrs9816** [comment]
I have similar problem too, it also appears in html-to-image package.

Sometimes width of text element and width of container holding the text doesn't match and it causes text to line wrap.
In my case, it's fine on desktop browsers but breaks in mobile devices. Some devices are fine, some are not.

Added whitespace nowrap for temporary fix.

**Comment by qq15725** [comment]
初步判断应该是 svg+xml 的字体渲染和源 html 内的不一致

可能是 opentype 的 gsub 表部分逻辑浏览器渲染不一致导致的

https://learn.microsoft.com/en-us/typography/opentype/spec/gsub

此处发现一个相关的测试用例

https://github.com/qq15725/modern-screenshot/blob/v4.4.2/test/fixtures/dom.comment.html

在 4.4.1 版本（未移除注释）下能复现

**Comment by jsbmg** [comment]
Any other solutions to this? I tried `white-space: nowrap`. While this does prevent the line wrapping issue, it is necessary, for my case, to have the text wrap.

**Comment by qq15725** [comment]
If someone can provide a copy of the code, it can help me solve this problem

[Playground link](https://sfc.vuejs.org/#eNp9kk1r4zAQhv/KoEtTSKTC3rxJYA972MNCKe1NF9We2GqtDzRy0hD83zu247ZpoAaDNPPO885IOok/Mcp9h6IQayqTjRkIcxe32lsXQ8pwgiq4x3Dva+hhl4KDGxcqTH7FekRPTcg3X9QJd0sI/n/ofMbqo4Y9WKV9GTxlSCHkvy1sBvXido5WJpunh3+fYe0/QAtDR1/C4hY2WzhpD7Na7k3bIdeYg7HMODe7mCymLKN6/tdqGpGH401GF1uTkXcA68ruB9eNFlOhFlC2hugc0GKUsZCi8dv71hzrxJ1VzBwCI0MxZGTz2roaCkol158bZaLi7Fp9MeYt5WM79SAHo2m24TvYKjcF/Lq7i2+/52CDtm7yZbQfJxsxYimmi1g5E+ULBc8XOxL1OUFaFLOHFnwrw16LJudIhVK0K4fn8EIypFrxSiY+futQIrnVcwoHwsRgLZYz4+o1XBI7H19rWQanroR8XpSV9RW+SXfBZGPFRntMq4ScT5h+6vOb9KrXAcun1Iv+HadLAqE=)

**Comment by gantrol** [comment]
> If someone can provide a copy of the code, it can help me solve this problem
> 
> 
> 
> [Playground link](https://sfc.vuejs.org/#eNp9kk1r4zAQhv/KoEtTSKTC3rxJYA972MNCKe1NF9We2GqtDzRy0hD83zu247ZpoAaDNPPO885IOok/Mcp9h6IQayqTjRkIcxe32lsXQ8pwgiq4x3Dva+hhl4KDGxcqTH7FekRPTcg3X9QJd0sI/n/ofMbqo4Y9WKV9GTxlSCHkvy1sBvXido5WJpunh3+fYe0/QAtDR1/C4hY2WzhpD7Na7k3bIdeYg7HMODe7mCymLKN6/tdqGpGH401GF1uTkXcA68ruB9eNFlOhFlC2hugc0GKUsZCi8dv71hzrxJ1VzBwCI0MxZGTz2roaCkol158bZaLi7Fp9MeYt5WM79SAHo2m24TvYKjcF/Lq7i2+/52CDtm7yZbQfJxsxYimmi1g5E+ULBc8XOxL1OUFaFLOHFnwrw16LJudIhVK0K4fn8EIypFrxSiY+futQIrnVcwoHwsRgLZYz4+o1XBI7H19rWQanroR8XpSV9RW+SXfBZGPFRntMq4ScT5h+6vOb9KrXAcun1Iv+HadLAqE=)


这个网站一堆 shawdowdom，我个人不知道怎么下载。

如果你的 Bing 账号还没通过，那可以试试这个方法:
- 新注册一个 hotmail 或 outlook 账号
- 换日本节点，去必应预约

前两周是秒通过的，不知道现在怎样

**Comment by jsbmg** [comment]
> If someone can provide a copy of the code, it can help me solve this problem
> 
> [Playground link](https://sfc.vuejs.org/#eNp9kk1r4zAQhv/KoEtTSKTC3rxJYA972MNCKe1NF9We2GqtDzRy0hD83zu247ZpoAaDNPPO885IOok/Mcp9h6IQayqTjRkIcxe32lsXQ8pwgiq4x3Dva+hhl4KDGxcqTH7FekRPTcg3X9QJd0sI/n/ofMbqo4Y9WKV9GTxlSCHkvy1sBvXido5WJpunh3+fYe0/QAtDR1/C4hY2WzhpD7Na7k3bIdeYg7HMODe7mCymLKN6/tdqGpGH401GF1uTkXcA68ruB9eNFlOhFlC2hugc0GKUsZCi8dv71hzrxJ1VzBwCI0MxZGTz2roaCkol158bZaLi7Fp9MeYt5WM79SAHo2m24TvYKjcF/Lq7i2+/52CDtm7yZbQfJxsxYimmi1g5E+ULBc8XOxL1OUFaFLOHFnwrw16LJudIhVK0K4fn8EIypFrxSiY+futQIrnVcwoHwsRgLZYz4+o1XBI7H19rWQanroR8XpSV9RW+SXfBZGPFRntMq4ScT5h+6vOb9KrXAcun1Iv+HadLAqE=)

I'm trying to replicate the issue, but I'm unable to get modern-screenshot to load the custom font:
[Playground](https://play.vuejs.org/#eNp9VE1v2zAM/SuEgS0pENvZBuzgJdl22KGHYsXQ3XQRbNlRZkuCSCc1gvz3Uf5I0jWrD7bE98T3RBI+Rt+dS/atirJohbnXjgAVtW4jjG6c9QRHKGzzZB9NBScovW1g1thCeRMzXymDW0uzK7ZX5QKsebCtIVWcz7AGs4TJrUECby39qGEd2PO7KVpIkr9/3V/CwpwTzSV2Jof5Haw3cBQGJnayl3Wr+Iw8SM05RrPzQWJA774Ic+J8q3S4I9+ON6QaV0tSvANYFXofZNciGk6KCPJaIo4BEfW0kTgh7JukNsr/bEn5M+d/rHvDrwtLEKzQSbN5rGVXeb5owQ5DYCCc8SeFdI0wwBI3oQCkLD65Pa+nVb/WTQUZ+pzNjWXk66aMrtKrqvAWqauHAn0bO9z6ej7bEjnM0rTkm2FSWVvVSjqNSW6bNEf8+LWUja679UMgKO8lvS80cuJujQfpZqEjAEmo7NDN8Bx0QdsMPi2X7rnHw7NVutrSy6igIBwPGhlcRBaA0mDMG12O3FP49GIvm3WRHY1lUNbqSoE3caG9yklbk0Fu67YxIzw6/bBcvusjN0T6Xk8i//IBnCwKbaoMPk+RWzbeNLFrkXTZxUFSGS5Rz0aSnt42FaZlclZzOL7UeCwxH+Wh6nsfLaKh83EjXbJDa/hf0R8WI4AiyqZ0Inr1cwioiKaJaY37U/Vj8orIA4qUalOo56TZcdbRySk6/QX0mJCi)

Not sure how to get the font "Montserrat" loaded in this playground example. I'm able to do it on my own code, it's just not working here (I'm not very familiar with Vue). The problem only occurs when I'm using a custom font. If I disable fonts (like it is here), there is no problem.

**Comment by qq15725** [comment]
It seems normal [Codepen html playground](https://codepen.io/qq15725/pen/VwGeqwa)

**Comment by Flourad** [comment]
> it

您好 打扰了
<img width="171" alt="image" src="https://github.com/qq15725/modern-screenshot/assets/1535874/5a9faa72-bffe-4322-b003-977f64372a79">
我这个截图之后，也是这个换行错乱了，请问是什么原因呀？

**Comment by emmanuelpignat** [comment]
Hi @qq15725 and thanks for your amazing work !

I came across this problem which was coming with several font families, sizes, and weights. It occurs to me that it might be because of very small approximations which makes the text slightly bigger, overflow and being wrapped. I tried to make all font sizes smaller when rendering by only 0.01% and as far as I tested, all my problems are gone.

To do this, I just added the following code in function copyCssStyles : 

```javascript
const fs = style.get('font-size')
if(fs){
	const value = splitValueAndUnit(fs[0])
	style.set('font-size', [value.value * 0.9999 + value.unit, ''])
}
```

I'll tell you if I see the problem appearing again.

**Comment by kvindascr** [comment]
I was facing this issue and solved it inspired on @emmanuelpignat solution.
In my case, I have guaranteed that all the CSS font units are in pixels due to the way the theme is structured, so it's easier to solve the issue.

I'm using the `onCloneNode` listener, to update the cloned node and reduce the font-sizes by 1px.

```
const imageDataUrl = await domToDataUrl(elemRef.current, {
    //... otherOptionsHere
    onCloneNode: (node) => {
        normalizeDomNodeForSvgScreenshot(node as HTMLElement);
    },
});


export function splitCssValueAndUnit(cssValue: string) {
    const regex = /^(-?\d*\.?\d+)([a-zA-Z%]*)$/;
    const match = cssValue.match(regex);

    if (match) {
        const numericValue = parseFloat(match[1]);
        const unit = match[2];
        return { value: numericValue, unit: unit };
    } else {
        throw new Error('Invalid CSS value format');
    }
}

export const normalizeDomNodeForSvgScreenshot = (node: HTMLElement) => {
    const fontSize = node.style.fontSize;
    if (fontSize) {
        try {
            const { value, unit } = splitCssValueAndUnit(fontSize);
            node.style.fontSize = `${value - 1}${unit}`; // Reducing font-size by 1px
        } catch (err) {
            // Ignore
        }
    }
    for (const childNode of node.children) {
        normalizeDomNodeForSvgScreenshot(childNode as HTMLElement);
    }
};      
```

I hope this can be of help for some of the folks dealing with this issue.

**Comment by qq15725** [comment]
fix #104
