### ISSUE TITLE
unable to render scrolling position

### ISSUE THREAD

**Issue by BugCreators** [qq15725/modern-screenshot#85]
Same question in [bubkoo/html-to-image#81](https://github.com/bubkoo/html-to-image/issues/81)

And, I noticed there's a [PR#209](https://github.com/bubkoo/html-to-image/pull/209)  attempting to solve this problem, I implemented it on [my fork](https://github.com/BugCreators/modern-screenshot/commit/ad9168f5def251d5e7e56f0975c9f156ed7f3c12).

The effect is as follows:

![1](https://github.com/qq15725/modern-screenshot/assets/33708320/543cd7d7-709a-4794-8c43-4106f144c67b)

Can I make a PR? I may need help adding test cases as I am unable to run the test

### Steps To Reproduce

[Playground for https://codesandbox.io](https://codesandbox.io/p/sandbox/modern-screenshot-5ydhjj?file=%2Findex.html%3A42%2C18)

### Your Environment

- modern-screenshot: 4.4.33
- Browser: Chrome/123.0.0.0

**Comment by qq15725** [comment]
Good, welcome to submit PR, but I prefer to move the option to [`features`](https://github.com/qq15725/modern-screenshot/blob/main/src/options.ts#L141C3-L141C11)

**Comment by qq15725** [comment]
#52 #78
