### ISSUE TITLE
能不能不要加载css中的所有字体

### ISSUE THREAD

**Issue by tohsakrat** [qq15725/modern-screenshot#88]
网站导入了类似easyfonts和fonts.css的库，现在每次截图网络请求里都会把所有自己全部加载一遍，非常痛苦………………
https://gitcode.com/zenozeng/fonts.css/overview?utm_source=artical_gitcode&isLogin=1

**Comment by qq15725** [comment]
```ts
domToPng(dom, {
  font: false
})
```

**Comment by tohsakrat** [comment]
不行啊，这样会导致所有额外字体都不加载。现在的问题是不管用没用的字体都被加载了拖慢速度。能不能只加载用上的
