### ISSUE TITLE
onCloneNode回调内修改样式以及追加dom元素后，截图没有效果，应当等待onCloneNode回调执行完毕后，再继续执行截图

### ISSUE THREAD

**Issue by zqianling** [qq15725/modern-screenshot#92]
### Steps To Reproduce
onCloneNode回调内修改样式以及追加dom元素后，截图没有效果，应当等待onCloneNode回调执行完毕后，再继续执行截图逻辑，html2canvas是有此逻辑的。

**Comment by qq15725** [comment]
merged
